@startuml

<style>
title {
  FontSize 16
  FontColor Black
  BackgroundColor Red
}
footer {
  HorizontalAlignment left
  FontSize 11
  FontColor red
}
</style>

title Onion Architecture Module Dependencies

component CORE #orange

component APPLICATION #yellow

component INFRASTRUCTURE #lightblue

component DEMO #lightgray

  DEMO -[#blue,bold]-> INFRASTRUCTURE
  DEMO -[#blue,bold]-> APPLICATION
  DEMO -[#blue,bold]-> CORE

  INFRASTRUCTURE -[#blue,bold]-> APPLICATION
  INFRASTRUCTURE -[#blue,bold]-> CORE

  APPLICATION -[#blue,bold]-> CORE

footer
© 2022 Thomas Herrmann, 42ways GmbH
endfooter

@enduml
