@startuml

'© 2022 Thomas Herrmann, 42ways GmbH

<style>
title {
  FontSize 24
  FontColor Black
  BackgroundColor Red
}
footer {
  HorizontalAlignment left
  FontSize 18
  FontColor red
}
</style>

' skinparam linetype ortho
' skinparam titleBorderRoundCorner 15
' skinparam titleBorderThickness 2
' skinparam titleBorderColor red
' skinparam titleBackgroundColor Red

title Onion Architecture Example

' -------------------------

component CORE #orange {

  package de.fourtytwoways.onion.domain.entities.contract {
    class de.fourtytwoways.onion.domain.entities.contract.Contract {
    }
  }
  

  package de.fourtytwoways.onion.domain.entities.document {
    interface de.fourtytwoways.onion.domain.entities.document.Document {
    }
  }
  

  package de.fourtytwoways.onion.domain.entities.enumeration {
    abstract class de.fourtytwoways.onion.domain.entities.enumeration.AbstractEnumValue {
    }
  }
  

  package de.fourtytwoways.onion.domain.entities.enumeration {
    class de.fourtytwoways.onion.domain.entities.enumeration.BonusSystem {
    }
  }
  

  package de.fourtytwoways.onion.domain.entities.enumeration {
    class de.fourtytwoways.onion.domain.entities.enumeration.DocumentType {
    }
  }
  

  package de.fourtytwoways.onion.domain.entities.enumeration {
    enum EnumType {
    }
  }
  

  package de.fourtytwoways.onion.domain.entities.enumeration {
    interface de.fourtytwoways.onion.domain.entities.enumeration.EnumValue {
    }
  }
  

  package de.fourtytwoways.onion.domain.entities.enumeration {
    class de.fourtytwoways.onion.domain.entities.enumeration.Product {
    }
  }
  

  package de.fourtytwoways.onion.domain.entities.enumeration {
    class de.fourtytwoways.onion.domain.entities.enumeration.Sex {
    }
  }
  

  package de.fourtytwoways.onion.domain.entities.enumeration {
    class de.fourtytwoways.onion.domain.entities.enumeration.Tariff {
    }
  }
  

  package de.fourtytwoways.onion.domain.entities.person {
    class de.fourtytwoways.onion.domain.entities.person.Address {
    }
  }
  

  package de.fourtytwoways.onion.domain.entities.person {
    class de.fourtytwoways.onion.domain.entities.person.Person {
    }
  }
  

  package de.fourtytwoways.onion.domain.usecases.contract {
    class de.fourtytwoways.onion.domain.usecases.contract.ContractCalculation {
    }
  }
  

  package de.fourtytwoways.onion.domain.usecases.contract {
    class de.fourtytwoways.onion.domain.usecases.contract.ContractDurationChange {
    }
  }
  

  de.fourtytwoways.onion.domain.entities.contract.Contract o-- de.fourtytwoways.onion.domain.entities.enumeration.Product : product
  de.fourtytwoways.onion.domain.entities.enumeration.AbstractEnumValue .up.|> de.fourtytwoways.onion.domain.entities.enumeration.EnumValue
  de.fourtytwoways.onion.domain.entities.enumeration.AbstractEnumValue o-- de.fourtytwoways.onion.domain.entities.enumeration.EnumType : type
  de.fourtytwoways.onion.domain.entities.enumeration.BonusSystem -up-|> de.fourtytwoways.onion.domain.entities.enumeration.AbstractEnumValue
  de.fourtytwoways.onion.domain.entities.enumeration.DocumentType -up-|> de.fourtytwoways.onion.domain.entities.enumeration.AbstractEnumValue
  de.fourtytwoways.onion.domain.entities.enumeration.Product -up-|> de.fourtytwoways.onion.domain.entities.enumeration.AbstractEnumValue
  de.fourtytwoways.onion.domain.entities.enumeration.Sex -up-|> de.fourtytwoways.onion.domain.entities.enumeration.AbstractEnumValue
  de.fourtytwoways.onion.domain.entities.enumeration.Tariff -up-|> de.fourtytwoways.onion.domain.entities.enumeration.AbstractEnumValue
  de.fourtytwoways.onion.domain.entities.person.Person o-- de.fourtytwoways.onion.domain.entities.enumeration.Sex : sex

}

' -------------------------

component APPLICATION #yellow {

  package de.fourtytwoways.onion.application.repositories {
    abstract class de.fourtytwoways.onion.application.repositories.AbstractEnumRepository {
    }
  }
  

  package de.fourtytwoways.onion.application.repositories {
    interface de.fourtytwoways.onion.application.repositories.ContractRepository {
    }
  }
  

  package de.fourtytwoways.onion.application.repositories {
    interface de.fourtytwoways.onion.application.repositories.DocumentRepository {
    }
  }
  

  package de.fourtytwoways.onion.application.repositories {
    interface de.fourtytwoways.onion.application.repositories.EnumRepository {
    }
  }
  

  package de.fourtytwoways.onion.application.repositories {
    interface de.fourtytwoways.onion.application.repositories.PersonRepository {
    }
  }
  

  package de.fourtytwoways.onion.application.repositories {
    interface de.fourtytwoways.onion.application.repositories.Repository {
    }
  }
  

  package de.fourtytwoways.onion.application.repositories {
    class de.fourtytwoways.onion.application.repositories.RepositoryRegistry {
    }
  }
  

  package de.fourtytwoways.onion.application.usecases.contract {
    abstract class de.fourtytwoways.onion.application.usecases.contract.AbstractContractModificationService {
    }
  }
  

  package de.fourtytwoways.onion.application.usecases.contract {
    class de.fourtytwoways.onion.application.usecases.contract.AdjustEndDateService {
    }
  }
  

  package de.fourtytwoways.onion.application.usecases.contract {
    class de.fourtytwoways.onion.application.usecases.contract.AdjustStartDateService {
    }
  }
  

  package de.fourtytwoways.onion.application.usecases.contract {
    class de.fourtytwoways.onion.application.usecases.contract.ChangeBenefitService {
    }
  }
  

  package de.fourtytwoways.onion.application.usecases.contract {
    class de.fourtytwoways.onion.application.usecases.contract.ChangePremiumService {
    }
  }
  

  de.fourtytwoways.onion.application.repositories.AbstractEnumRepository .up.|> de.fourtytwoways.onion.application.repositories.EnumRepository
  de.fourtytwoways.onion.application.usecases.contract.AdjustEndDateService -up-|> de.fourtytwoways.onion.application.usecases.contract.AbstractContractModificationService
  de.fourtytwoways.onion.application.usecases.contract.AdjustStartDateService -up-|> de.fourtytwoways.onion.application.usecases.contract.AbstractContractModificationService
  de.fourtytwoways.onion.application.usecases.contract.ChangeBenefitService -up-|> de.fourtytwoways.onion.application.usecases.contract.AbstractContractModificationService
  de.fourtytwoways.onion.application.usecases.contract.ChangePremiumService -up-|> de.fourtytwoways.onion.application.usecases.contract.AbstractContractModificationService

}

' -------------------------

component INFRASTRUCTURE #lightblue {

  package de.fourtytwoways.onion.infrastructure.contracts.db {
    class de.fourtytwoways.onion.infrastructure.contracts.db.ContractDAO {
    }
  }
  

  package de.fourtytwoways.onion.infrastructure.contracts.db {
    class de.fourtytwoways.onion.infrastructure.contracts.db.ExampleContractRepository {
    }
  }
  

  package de.fourtytwoways.onion.infrastructure.database {
    class de.fourtytwoways.onion.infrastructure.database.SessionFactory {
    }
  }
  

  package de.fourtytwoways.onion.infrastructure.documents {
    class de.fourtytwoways.onion.infrastructure.documents.ExampleDocumentRepository {
    }
  }
  

  package de.fourtytwoways.onion.infrastructure.documents {
    class de.fourtytwoways.onion.infrastructure.documents.ExamplePolicyDocument {
    }
  }
  

  package de.fourtytwoways.onion.infrastructure.enums.provider {
    class de.fourtytwoways.onion.infrastructure.enums.provider.EnumValueDAO {
    }
  }
  

  package de.fourtytwoways.onion.infrastructure.enums.provider {
    class de.fourtytwoways.onion.infrastructure.enums.provider.ExampleEnumProviderOne {
    }
  }
  

  package de.fourtytwoways.onion.infrastructure.enums.provider {
    class de.fourtytwoways.onion.infrastructure.enums.provider.ExampleEnumProviderTwo {
    }
  }
  

  package de.fourtytwoways.onion.infrastructure.enums.provider {
    class de.fourtytwoways.onion.infrastructure.enums.provider.ExampleEnumRepository {
    }
  }
  

  package de.fourtytwoways.onion.infrastructure.people.db {
    class de.fourtytwoways.onion.infrastructure.people.db.AddressDAO {
    }
  }
  

  package de.fourtytwoways.onion.infrastructure.people.db {
    class de.fourtytwoways.onion.infrastructure.people.db.ExamplePersonRepository {
    }
  }
  

  package de.fourtytwoways.onion.infrastructure.people.db {
    class de.fourtytwoways.onion.infrastructure.people.db.PersonDAO {
    }
  }
  

  de.fourtytwoways.onion.infrastructure.contracts.db.ContractDAO -up-|> de.fourtytwoways.onion.domain.entities.contract.Contract
  de.fourtytwoways.onion.infrastructure.contracts.db.ExampleContractRepository .up.|> de.fourtytwoways.onion.application.repositories.ContractRepository
  de.fourtytwoways.onion.infrastructure.documents.ExampleDocumentRepository .up.|> de.fourtytwoways.onion.application.repositories.DocumentRepository
  de.fourtytwoways.onion.infrastructure.documents.ExamplePolicyDocument .up.|> de.fourtytwoways.onion.domain.entities.document.Document
  de.fourtytwoways.onion.infrastructure.documents.ExamplePolicyDocument o-- de.fourtytwoways.onion.domain.entities.contract.Contract : contract
  de.fourtytwoways.onion.infrastructure.enums.provider.ExampleEnumRepository -up-|> de.fourtytwoways.onion.application.repositories.AbstractEnumRepository
  de.fourtytwoways.onion.infrastructure.enums.provider.ExampleEnumRepository o-- de.fourtytwoways.onion.infrastructure.enums.provider.ExampleEnumProviderOne : providerOne
  de.fourtytwoways.onion.infrastructure.enums.provider.ExampleEnumRepository o-- de.fourtytwoways.onion.infrastructure.enums.provider.ExampleEnumProviderTwo : providerTwo
  de.fourtytwoways.onion.infrastructure.people.db.AddressDAO o-- de.fourtytwoways.onion.infrastructure.people.db.PersonDAO : personDAO
  de.fourtytwoways.onion.infrastructure.people.db.ExamplePersonRepository .up.|> de.fourtytwoways.onion.application.repositories.PersonRepository
  de.fourtytwoways.onion.infrastructure.people.db.ExamplePersonRepository o-- de.fourtytwoways.onion.application.repositories.EnumRepository : enumRepository

}

' -------------------------

component MAIN #lightgray {

  package de.fourtytwoways.onion {
    class de.fourtytwoways.onion.ContractDemo {
    }
  }
  

  package de.fourtytwoways.onion {
    class de.fourtytwoways.onion.EnumDemo {
    }
  }
  

  package de.fourtytwoways.onion {
    class de.fourtytwoways.onion.PersonDemo {
    }
  }
  


}

' -------------------------

  MAIN -[#blue,bold]-> INFRASTRUCTURE
  MAIN -[#blue,bold]-> APPLICATION
  MAIN -[#blue,bold]-> CORE

  INFRASTRUCTURE -[#blue,bold]-> APPLICATION
  INFRASTRUCTURE -[#blue,bold]-> CORE

  APPLICATION -[#blue,bold]-> CORE

footer
© 2022 Thomas Herrmann, 42ways GmbH
endfooter

@enduml
