# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    - name: Generate Overall Test and Coverage Reports
      uses: gradle/gradle-build-action@v2
      with:
        arguments: jacocoTestReport testReport
    - name: Archive Test Report
      uses: actions/upload-artifact@v3
      with:
        name: Onion CI Reports
        path: build/reports
    - name: Generate Architecture Diagrams
      uses: gradle/gradle-build-action@v2
      with:
        arguments: archidoc
    - name: Archive Architecture Documents
      uses: actions/upload-artifact@v3
      with:
        name: Onion Architecture Documents
        path: build/architecture
